language: csharp
solution: FizzBuzz.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore FizzBuzz.sln
after_script:
  - nunit-console FizzBuzzTests/bin/Release/FizzBuzzTests.dll
