language: csharp
solution: FizzBuzz.sln
install:
  - nuget restore FizzBuzz.sln
  - nuget install NUnit.Runners -Version 3.2.1 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release FizzBuzz.sln
  - mono ./testrunner/NUnit.Runners.3.2.1/tools/nunit-console.exe ./FizzBuzzTests/bin/Release/FizzBuzzTests.dll
