language: csharp
solution: FizzBuzz.sln
install:
  - nuget restore FizzBuzz.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release FizzBuzz.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./FizzBuzzTests/bin/Release/FizzBuzzTests.dll
